services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      # - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_db
      
    command: ["./wait-for-it.sh", "db:5432", "--", "python3", "manage.py", "runserver", "0.0.0.0:8000"]
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  bot:
    build: .
    command: python3 bot/main.py
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_db

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  # celery:
  #   build: .
  #   command: celery -A spendsense worker --loglevel=info
  #   depends_on:
  #     - redis
  #     - db
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_db
  # flower:
  #   image: mher/flower
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     - redis
volumes:
  postgres_data: