# Generated by Django 3.1.12 on 2025-04-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='time_create',
        ),
        migrations.AddField(
            model_name='transaction',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
