# Generated by Django 3.1.12 on 2025-05-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='spent',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
