# Generated by Django 3.1.12 on 2025-05-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_transaction_spent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='spent',
            new_name='is_spent',
        ),
    ]
