# Generated by Django 3.1.12 on 2025-05-26 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnings',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='spents', to='finance.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spents',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='finance.account'),
            preserve_default=False,
        ),
    ]
