# Generated by Django 3.1.12 on 2025-05-05 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20250505_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.transaction')),
            ],
            bases=('finance.transaction',),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_spent',
        ),
    ]
