# Generated by Django 5.2.3 on 2025-08-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_account_unique_name_per_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='api_key',
        ),
    ]
