# Generated by Django 3.1.12 on 2025-05-26 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20250526_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnings',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='spents',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spents', to='finance.account'),
        ),
        migrations.CreateModel(
            name='SpentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spent_cat', to='finance.account')),
            ],
        ),
        migrations.CreateModel(
            name='EarnCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earn_cat', to='finance.account')),
            ],
        ),
    ]
