# Generated by Django 3.1.12 on 2025-05-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20250526_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earncategory',
            name='icon',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='spentcategory',
            name='icon',
            field=models.CharField(max_length=3),
        ),
    ]
