# Generated by Django 3.1.12 on 2025-05-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20250526_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earncategory',
            name='account',
        ),
        migrations.RemoveField(
            model_name='spentcategory',
            name='account',
        ),
    ]
