# Generated by Django 3.1.12 on 2025-05-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_usercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategory',
            name='is_spent',
            field=models.CharField(choices=[('spent', 'Spent'), ('earn', 'Earn')], default='spent', max_length=20),
        ),
    ]
