# Generated by Django 3.1.12 on 2025-05-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_usercategory_is_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnings',
            name='time_create',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='time_update',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='spents',
            name='time_create',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='spents',
            name='time_update',
            field=models.DateTimeField(),
        ),
    ]
