# Generated by Django 3.1.12 on 2025-06-04 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_auto_20250528_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monotoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='MonoAccount',
        ),
        migrations.DeleteModel(
            name='MonoToken',
        ),
    ]
